### ISSUE TITLE
DragSelectionUpdateCallback not found - BREAKING AFTER FLUTTER UPGRADE

### ISSUE THREAD

**Issue by Mmisiek** [singerdmx/flutter-quill#1209]
Package fails to compile after flutter upgrade:
: Error: Type 'DragSelectionUpdateCallback' not found.
text_selection.dart:771
  final DragSelectionUpdateCallback? onDragSelectionUpdate;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
raw_editor.dart:240
 - TextInputClient.insertContent

The package analytics on pub.dev also shows failure :(
https://pub.dev/packages/flutter_quill/score

This is breaking my app :(

**Comment by Ajay9o9** [comment]
Getting same error here as well.

`Launching lib/main_dev.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...
../../.pub-cache/hosted/pub.dev/flutter_quill-7.1.17+1/lib/src/widgets/text_selection.dart:716:9: Error: Type 'DragSelectionUpdateCallback' not found.
  final DragSelectionUpdateCallback? onDragSelectionUpdate;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/flutter_quill-7.1.17+1/lib/src/widgets/text_selection.dart:716:9: Error: 'DragSelectionUpdateCallback' isn't a type.
  final DragSelectionUpdateCallback? onDragSelectionUpdate;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/flutter_quill-7.1.17+1/lib/src/widgets/raw_editor.dart:277:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextInputClient.insertContent
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
`
Running on latest version of flutter. 

`Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84a1e904f4 (2 days ago) • 2023-05-09 07:41:44 -0700
Engine • revision d44b5a94c9
Tools • Dart 3.0.0 • DevTools 2.23.1
`

**Comment by Mmisiek** [comment]
I fixed in: https://github.com/Mmisiek/flutter-quill.git

**Comment by sunnykinger** [comment]
same issue. Will try this PR and see if this helps

**Comment by adil192** [comment]
@singerdmx I'm still experiencing this issue after `flutter_quill: 7.1.17+1`:
```Launching lib\main.dart on Windows in debug mode...
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-7.1.17+1/lib/src/widgets/text_selection.dart(716,9): error G5FE39F1E: Type 'DragSelectionUpdateCallback' not found. [C:\Users\adilh\Documents\GitHub\saber\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-7.1.17+1/lib/src/widgets/raw_editor.dart(277,7): error G76B49859: The non-abstract class 'RawEditorState' is missing implementations for these members: [C:\Users\adilh\Documents\GitHub\saber\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dev/screenshot-1.3.0/lib/screenshot.dart(160,7): error GC6690633: No named parameter with the name 'window'. [C:\Users\adilh\Documents\GitHub\saber\build\windows\flutter\flutter_assemble.vcxproj]
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-7.1.17+1/lib/src/widgets/text_selection.dart(716,9): error G9B3D8C68: 'DragSelectionUpdateCallback' isn't a type. [C:\Users\adilh\Documents\GitHub\saber\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'C:\Users\adilh\Documents\GitHub\saber\build\windows\CMakeFiles\fb8fe2dbd8e12b
0697a675fb01bf473c\flutter_windows.dll.rule;C:\Users\adilh\Documents\GitHub\saber\build\windows\CMakeFiles\d9012f90891ce70ee21846a3c69bf2b8\flutter_assemble.rule;C:\Users\adilh\Documents\GitHub\saber\windows\flutter\CMakeLists.txt' exited with code 1. [C:\Users\adilh\Documents\GitHub\saber\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...                                   118.2s
Exception: Build process failed.
```

The static analysis fails with the same error on https://pub.dev/packages/flutter_quill/score

**Comment by Mmisiek** [comment]
> @singerdmx I'm still experiencing this issue after `flutter_quill: 7.1.17+1`:
> 
> ```
> ../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-7.1.17+1/lib/src/widgets/text_selection.dart(716,9): error G5FE39F1E: Type 'DragSelectionUpdateCallback' not found. [C:\Users\adilh\Documents\GitHub\saber\build\windows\flutter\flutter_assemble.vcxproj]
> ../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-7.1.17+1/lib/src/widgets/raw_editor.dart(277,7): error G76B49859: The non-abstract class 'RawEditorState' is missing implementations for these members: [C:\Users\adilh\Documents\GitHub\saber\build\windows\flutter\flutter_assemble.vcxproj]
> ../../../AppData/Local/Pub/Cache/hosted/pub.dev/screenshot-1.3.0/lib/screenshot.dart(160,7): error GC6690633: No named parameter with the name 'window'. [C:\Users\adilh\Documents\GitHub\saber\build\windows\flutter\flutter_assemble.vcxproj]
> ../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-7.1.17+1/lib/src/widgets/text_selection.dart(716,9): error G9B3D8C68: 'DragSelectionUpdateCallback' isn't a type. [C:\Users\adilh\Documents\GitHub\saber\build\windows\flutter\flutter_assemble.vcxproj]
> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'C:\Users\adilh\Documents\GitHub\saber\build\windows\CMakeFiles\fb8fe2dbd8e12b
> 0697a675fb01bf473c\flutter_windows.dll.rule;C:\Users\adilh\Documents\GitHub\saber\build\windows\CMakeFiles\d9012f90891ce70ee21846a3c69bf2b8\flutter_assemble.rule;C:\Users\adilh\Documents\GitHub\saber\windows\flutter\CMakeLists.txt' exited with code 1. [C:\Users\adilh\Documents\GitHub\saber\build\windows\flutter\flutter_assemble.vcxproj]
> Building Windows application...                                   118.2s
> Exception: Build process failed.
> ```
> 
> The static analysis fails with the same error on https://pub.dev/packages/flutter_quill/score

There is no new build, you need to use version from GIT.

**Comment by singerdmx** [comment]
You can raise a PR to bump the version

**Comment by Mmisiek** [comment]
Somehow I thought that version update was part of PR merging.  When creating PR one does not know when it will be merged. Shall I create another PR with version bump ?

**Comment by singerdmx** [comment]
Yes please update changelog as well
