### ISSUE TITLE
Issue with checkbox value changes, search bar UI, cursor

### ISSUE THREAD

**Issue by milindgoel15** [singerdmx/flutter-quill#1440]
Some issues on android platform:

- So whenever I change the value of the checkbox, the keyboard pops up if it was hidden. Could you do something such that, if the checkbox value is changed and keyboard is not in focus, it doesn't pop up. As many times, when we are editing a note, we are only updating the checkbox list and we don't require keyboard to come in focus. 

So something like a Boolean could be suitable. `shouldKeyboardComeInFocus` something like this.

- The searchbar UI of the toolbar is really terrible.
![image](https://github.com/singerdmx/flutter-quill/assets/45682747/5d0b090c-5376-43e6-ab44-a51ec48c85a0)

- when typing in the editor, if we unfocus the keyboard and start typing again, the caret/cursor becomes invisible.

<details>
<summary>video demo:</summary>

https://github.com/singerdmx/flutter-quill/assets/45682747/7a13f49c-064e-491b-95ec-bb9ccfa2d1b7

</details>

_Originally posted in https://github.com/singerdmx/flutter-quill/issues/1431#issuecomment-1770855232_

**Comment by freshtechtips** [comment]
Hi, we are working on a major update to make this library extremely customizable so you can customize everything from the UI to fit your needs, remember?? we talked about this in the discussions

but I don't see any checkbox or checklist in there
can you explain more?

**Comment by milindgoel15** [comment]
> but I don't see any checkbox or checklist in there

This checkbox:

![Screenshot_2023-10-20-17-20-30-244_com.mgprojects.todoify-edit.jpg](https://github.com/singerdmx/flutter-quill/assets/45682747/7ee5fa67-c0f3-4401-992f-1dc7b972df25)

<details>
<summary>video demo</summary>

https://github.com/singerdmx/flutter-quill/assets/45682747/a980b04a-8c7b-4ed5-92f3-66c4cccd51d2


</details>

**Comment by freshtechtips** [comment]
I understand now, I will look into it!

**Comment by freshtechtips** [comment]
@singerdmx 
I make the default value to not request the keyboard when the checklist value is changed because it's quite annoying as you can see in the video but it always gets the keyboard back

don't worry we will provide the option to customize this in the next major update but for now, we will fix this because it's not good at all, ask anyone if he wants the keyboard to be requested when the checklist values are changed while the keyboard is not there and he will tell you no he don't want that behavior, try it out by yourself in any mobile device to see what I mean

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/fa046f5f-8765-4593-8b00-2e273a7c7d27)

And it will only work when I remove the code
```dart
controller.skipRequestKeyboard = false;
```
in the if statement is true

and the print statement gets called 2-4 times just by one simple change on the checkbox
is that normal or it's a bug that we should look into it deeper??

**Comment by milindgoel15** [comment]
I think it might need to be refractored to fit all the use cases while on the mobile platform;

- where only the checklist item is being changed:
-- If `showKeyboardOnChecklistValueChange` == false:
Don't show the keyboard on the checklist value modification
Don't show caret
And return out of the function
-- else 
show keyboard and return out.


- where user focuses the editor to enter some input:
Show the caret and keyboard

- where user unfocus the editor:
Removes the caret and keyboard

**Comment by freshtechtips** [comment]
> I think it might need to be refractored to fit all the use cases while on the mobile platform;
> 
> * where only the checklist item is being changed:
> 
> ```
>  If `showKeyboardOnChecklistValueChange` == false:
> Don't show the keyboard on the checklist value modification
> Don't show caret
> And return out of the function
> 
> else show keyboard and return out.
> ```
> 
> * where user focuses the editor to enter some input:
>   Show the caret and keyboard
> * where user unfocus the editor:
>   Removes the caret and keyboard
> 
> And ofcourse other use cases.

It's not that easy, everything is abstracted and passed using constructors which is a pain to add new features
which is why I suggest to refactor the whole library with major update

**Comment by freshtechtips** [comment]
I fixed it but I might break something else or introduce new bugs so I reverted the changes back

I will look into this in the next major update

**Comment by milindgoel15** [comment]
> I might break something else or introduce new bugs so I reverted the changes back

You could like create a new branch and push these issue fixes to it. So until the next major update, I will pull changes from your branch and use it locally.

**Comment by freshtechtips** [comment]
This issue will probably get fixed in the next pull request or the one after it

**Comment by freshtechtips** [comment]
We have solved this issue and we added a callback to show a custom dialog, also a new childBuilder in `QuillToolbarSearchButton` has been added

if you still face this issue or any others
Do not hesitate to contact us

**Comment by milindgoel15** [comment]
The checkbox keyboard issue still happens on 7.10.2 version. Doesnt matter `requestKeyboardFocusOnCheckListChanged` is true or false, keyboard still pops on android

**Comment by freshtechtips** [comment]
> The checkbox keyboard issue still happens on 7.10.2 version. Doesnt matter `requestKeyboardFocusOnCheckListChanged` is true or false, keyboard still pops on android

That is because there is another bug internally, but in most cases, the keyboard won't pop up

**Comment by milindgoel15** [comment]
> That is because there is another bug internally,

Well, in that case, this issue should be reopened. There's no point in closing the issue if the solution does not yet work.

**Comment by freshtechtips** [comment]
> > That is because there is another bug internally,
> 
> Well, in that case, this issue should be reopened. There's no point in closing the issue if the solution does not yet work.

Most of the issues you mentioned here are solved

Even when you click the toggle checklist button

Except when you change their values in the editor in some cases

It can be confusing, so I closed this issue

It's on our todo to fix every bug we notice

Feel free to open a new issue that is specific to the only issue that didn't get solved properly
