### ISSUE TITLE
[Mobile] history undo-redo throwing exception.

### ISSUE THREAD

**Issue by pavel-birdy** [singerdmx/flutter-quill#206]
My issue is about [Mobile]

I am getting this exception from undoing second time. And redo also giving the same error after that. 

```
E/MethodChannel#flutter/textinput(26978): Failed to handle method call
E/MethodChannel#flutter/textinput(26978): java.lang.IndexOutOfBoundsException: invalid composing start: 1485
E/MethodChannel#flutter/textinput(26978): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:719)
E/MethodChannel#flutter/textinput(26978): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/MethodChannel#flutter/textinput(26978): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/MethodChannel#flutter/textinput(26978): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/textinput(26978): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/textinput(26978): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter/textinput(26978): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/textinput(26978): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter/textinput(26978): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#flutter/textinput(26978): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#flutter/textinput(26978): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput(26978): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter/textinput(26978): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (26978): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, invalid composing start: 1485, null, java.lang.IndexOutOfBoundsException: invalid composing start: 1485
E/flutter (26978): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:719)
E/flutter (26978): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/flutter (26978): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/flutter (26978): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (26978): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (26978): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (26978): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (26978): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (26978): 	at android.os.Looper.loop(Looper.java:183)
E/flutter (26978): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (26978): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (26978): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (26978): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (26978): )
E/flutter (26978): #0      JSONMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:158
E/flutter (26978): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:158
```

**Comment by sorrychan** [comment]
I also faced another exception related to undoing.
[Steps to reproduce]
1.  Attach image in empty board. (Both selection and take photo occurred)
2.  Press the undo.
3.  Exception handling message below occurred.

════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'dart:ui/text.dart': Failed assertion: line 1504 pos 16: '<optimized out>': is not true.

When the exception was thrown, this was the stack
2      new TextRange.collapsed (dart:ui/text.dart:1504:16)
3      new TextSelection.collapsed
package:flutter/…/services/text_editing.dart:41
4      QuillController._handleHistoryChange
package:flutter_quill/widgets/controller.dart:74
5      QuillController.undo
package:flutter_quill/widgets/controller.dart:63
6      _HistoryButtonState._changeHistory
package:flutter_quill/widgets/toolbar.dart:806
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#ce968
    debugOwner: GestureDetector
    state: ready
    won arena
    finalPosition: Offset(113.4, 476.6)
    finalLocalPosition: Offset(19.9, 23.8)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════


════════ Exception caught by rendering library ═════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was
EditableTextLine
flutter_quill-1.2.2\…\widgets\raw_editor.dart:637
════════════════════════════════════════════════════════════════════════════════

This looks like cursor related problem. When writing any message and attach image, then doing undo with set the edit cursor behind the image, this exception did not occur. However, doing undo with before image, exception happens and edit cursor disappears.

**Comment by li3317** [comment]
Hello, the issue has been resolved. Thank you!

**Comment by rmRizki** [comment]
> Hello, the issue has been resolved. Thank you!

Hi, i'm still having this error when using undo-redo

`I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
E/flutter (10267): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, invalid selection start: 15, null, java.lang.IndexOutOfBoundsException: invalid selection start: 15
E/flutter (10267):      at io.flutter.embedding.engine.i.n$e.<init>(Unknown Source:103)
E/flutter (10267):      at io.flutter.embedding.engine.i.n$e.a(Unknown Source:33)
E/flutter (10267):      at io.flutter.embedding.engine.i.n$a.f(Unknown Source:385)
E/flutter (10267):      at g.a.d.a.j$a.a(Unknown Source:17)
E/flutter (10267):      at io.flutter.embedding.engine.e.b.e(Unknown Source:57)
E/flutter (10267):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (10267):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (10267):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (10267):      at android.os.Looper.loop(Looper.java:206)
E/flutter (10267):      at android.app.ActivityThread.main(ActivityThread.java:8506)
E/flutter (10267):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (10267):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (10267):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
E/flutter (10267): )
E/flutter (10267): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:164)
E/flutter (10267): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (10267): <asynchronous suspension>
E/flutter (10267): 
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
E/flutter (10267): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, invalid selection start: 15, null, java.lang.IndexOutOfBoundsException: invalid selection start: 15
E/flutter (10267):      at io.flutter.embedding.engine.i.n$e.<init>(Unknown Source:103)
E/flutter (10267):      at io.flutter.embedding.engine.i.n$e.a(Unknown Source:33)
E/flutter (10267):      at io.flutter.embedding.engine.i.n$a.f(Unknown Source:385)
E/flutter (10267):      at g.a.d.a.j$a.a(Unknown Source:17)
E/flutter (10267):      at io.flutter.embedding.engine.e.b.e(Unknown Source:57)
E/flutter (10267):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (10267):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (10267):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (10267):      at android.os.Looper.loop(Looper.java:206)
E/flutter (10267):      at android.app.ActivityThread.main(ActivityThread.java:8506)
E/flutter (10267):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (10267):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (10267):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
E/flutter (10267): )
E/flutter (10267): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:164)
E/flutter (10267): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (10267): <asynchronous suspension>
E/flutter (10267): 
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
E/flutter (10267): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, invalid selection start: 15, null, java.lang.IndexOutOfBoundsException: invalid selection start: 15
E/flutter (10267):      at io.flutter.embedding.engine.i.n$e.<init>(Unknown Source:103)
E/flutter (10267):      at io.flutter.embedding.engine.i.n$e.a(Unknown Source:33)
E/flutter (10267):      at io.flutter.embedding.engine.i.n$a.f(Unknown Source:385)
E/flutter (10267):      at g.a.d.a.j$a.a(Unknown Source:17)
E/flutter (10267):      at io.flutter.embedding.engine.e.b.e(Unknown Source:57)
E/flutter (10267):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (10267):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (10267):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (10267):      at android.os.Looper.loop(Looper.java:206)
E/flutter (10267):      at android.app.ActivityThread.main(ActivityThread.java:8506)
E/flutter (10267):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (10267):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (10267):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
E/flutter (10267): )
E/flutter (10267): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:164)
E/flutter (10267): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (10267): <asynchronous suspension>
E/flutter (10267): 
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
E/flutter (10267): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, invalid selection start: 10, null, java.lang.IndexOutOfBoundsException: invalid selection start: 10
E/flutter (10267):      at io.flutter.embedding.engine.i.n$e.<init>(Unknown Source:103)
E/flutter (10267):      at io.flutter.embedding.engine.i.n$e.a(Unknown Source:33)
E/flutter (10267):      at io.flutter.embedding.engine.i.n$a.f(Unknown Source:385)
E/flutter (10267):      at g.a.d.a.j$a.a(Unknown Source:17)
E/flutter (10267):      at io.flutter.embedding.engine.e.b.e(Unknown Source:57)
E/flutter (10267):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (10267):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (10267):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (10267):      at android.os.Looper.loop(Looper.java:206)
E/flutter (10267):      at android.app.ActivityThread.main(ActivityThread.java:8506)
E/flutter (10267):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (10267):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (10267):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
E/flutter (10267): )
E/flutter (10267): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:164)
E/flutter (10267): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (10267): <asynchronous suspension>
E/flutter (10267): 
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
E/flutter (10267): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, invalid selection start: 10, null, java.lang.IndexOutOfBoundsException: invalid selection start: 10
E/flutter (10267):      at io.flutter.embedding.engine.i.n$e.<init>(Unknown Source:103)
E/flutter (10267):      at io.flutter.embedding.engine.i.n$e.a(Unknown Source:33)
E/flutter (10267):      at io.flutter.embedding.engine.i.n$a.f(Unknown Source:385)
E/flutter (10267):      at g.a.d.a.j$a.a(Unknown Source:17)
E/flutter (10267):      at io.flutter.embedding.engine.e.b.e(Unknown Source:57)
E/flutter (10267):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (10267):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (10267):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (10267):      at android.os.Looper.loop(Looper.java:206)
E/flutter (10267):      at android.app.ActivityThread.main(ActivityThread.java:8506)
E/flutter (10267):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (10267):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (10267):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
E/flutter (10267): )
E/flutter (10267): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:164)
E/flutter (10267): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (10267): <asynchronous suspension>
E/flutter (10267): 
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (10267): Another exception was thrown: Instance of 'DiagnosticsPro`

**Comment by singerdmx** [comment]
Please submit a PR
We are Not going to address it any further
