### ISSUE TITLE
Text highlighting/selection issue with Flutter 3.27.2

### ISSUE THREAD

**Issue by bloemy7** [singerdmx/flutter-quill#2450]
### Have you checked for an existing issue?

- [x] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill Version

10.8.5

### Steps to Reproduce

1. Setup project with flutter-quill when running flutter version 3.27.2
2. Try highlighting text to select it

### Expected results

Expecting to be able to smoothly select text

### Actual results

Almost impossible to select text as it auto-select multiple lines in a very buggy way

### Additional Context

<details>
The issue seems to be around the precision of the cursor when selecting a line. If you put it exactly at the height of a line, it acts as if it was already slightly above the line, and so it automatically selects the full line. This makes the entire experience impossible to properly control.

I have downgraded Flutter to 3.27.1 and 3.27.0, but there when selecting text it doesn't show the resulting highlight as you are dragging, only once you release the drag, which is not a good experience either.

Any ideas?
</details>

**Comment by EchoEllet** [comment]
> 10.8.5

Could you try with `11.0.0-dev.20` (or later) as the magnifier has been removed and related issues have been fixed.

**Comment by bloemy7** [comment]
Hi @EchoEllet, just tried with 11.0.0-dev.21, and it's still happening for me unfortunately. 

https://github.com/user-attachments/assets/92c13c2c-5279-453e-82ed-7f320a73ab16

Any other ideas? Thanks!

**Comment by jonasbernardo** [comment]
I tested it here, on Android the selection with a bluetooth mouse works normally, the problem only happens in the web version, another problem is also when clicking on empty lines, the cursor always appears on the top line and not on the clicked line, but it needs to be between two text when there is an empty space

**Comment by jonasbernardo** [comment]
i use 11.0.0-dev.20

**Comment by jonasbernardo** [comment]
These 2 problems are big, which makes the web version very difficult to use, it should be fixed urgently
@EchoEllet 
@CatHood0

**Comment by bloemy7** [comment]
Yes that is a separate bug that is not related to flutter-quill at all, sorry for the confusion here. But it's a bug that forces us to update Flutter version, except that we cannot because of this bug @EchoEllet .

**Comment by CatHood0** [comment]
I cannot reproduce this issue.

**Comment by CatHood0** [comment]
I cannot reproduce this issue in Flutter 3.27.3 and the `11.0.0-dev.20`

**Comment by bloemy7** [comment]
@jonasbernardo are you able to reproduce as well with the above configuration?

**Comment by jonasbernardo** [comment]
yes, the problem persisted, I recorded a video running the example within the flutter quill package
@CatHood0 
@bloemy7 
@EchoEllet 

https://github.com/user-attachments/assets/a8da7fbb-1595-48dc-878a-f889ba77f396

**Comment by jonasbernardo** [comment]
I just forgot to activate the mouse pointer, but in the video I'm trying to select a word and it selects a bunch of things that I didn't select

**Comment by Heyholder** [comment]
i have same issue.  did you fix it?

https://github.com/user-attachments/assets/33cbd1f2-4881-4dc5-98b0-269f787a6413

**Comment by bloemy7** [comment]
I just tried with the latest Flutter 3.29.0 stable release and unfortunately this still reproduces. @CatHood0 are you maybe able to reproduce? Can this get investigated in some way? I'm happy to help contribute but not quite sure where to start on this issue.
This is causing major issue in production apps and seems to be widely reproducible on very basic configurations.

Thanks a lot.

**Comment by jonasbernardo** [comment]
@bloemy7 
@CatHood0 
@EchoEllet 
new information, the problem does not happen if you are using mozilla firefox, but if you are using google chrome this selection problem appears

**Comment by realth000** [comment]
Is this the same issue in flutter dev tools?

For example, in dev tools -> network -> select a request -> goto the Response tab on the right side, select some text and a similar issue occurs if the text is multi line.

* Flutter 3.29.0, Chrome on Windows.

**Comment by jonasbernardo** [comment]
update from my latest tests: text selection only works in mozilla firefox

**Comment by dominikkeller** [comment]
I am experiencing the same issue in all browsers except Safari and Firefox.
This is a significant issue for our application.

Flutter version: 3.27.2.

**Comment by hannutho** [comment]
@jonasbernardo 
@bloemy7 
@CatHood0 
@EchoEllet 
Safari on Mac also works.
Anyone found any workaround or fix for this?

**Comment by RJustoX** [comment]
Hi everyone, I'm encountering the same issue.

I noticed that adding the following code:

```
customStyles: DefaultStyles(
  paragraph: DefaultTextBlockStyle(
    // your textStyle
    const HorizontalSpacing(4, 4),
    const VerticalSpacing(4, 4),
    const VerticalSpacing(4, 4),
    null,
  ),
),
```

is causing the selection to extend four lines above the text I want to select. Without this, it only selects the line I want plus one. Has anyone else experienced this?

flutter 3.27.3 | quill 11.0.0 | testing on chrome

**Comment by bloemy7** [comment]
@CatHood0 it seems like this issue is becoming more widespread and probably should be more thoroughly investigated at this point as it makes the editor as such unusable. If anyone has any thoughts on how to proceed here it would be great...

**Comment by Heyholder** [comment]
below is my quillEditor setting.
`   final DefaultTextStyle defaultTextStyle = DefaultTextStyle.of(context);
    const HorizontalSpacing baseHorizontalSpacing = HorizontalSpacing(0, 0);
    const VerticalSpacing baseVerticalSpacing = VerticalSpacing(0, 12);
    return QuillEditor.basic(
      controller: quillController,
      configurations: QuillEditorConfigurations(
        minHeight: minHeight,
        embedBuilders: FlutterQuillEmbeds.editorWebBuilders(),
        showCursor: showCursor,
        padding: const EdgeInsets.all(16),
        placeholder: hintText,
        enableSelectionToolbar: false,
        customStyles: DefaultStyles(
          h1: DefaultTextBlockStyle(
              defaultTextStyle.style.copyWith(
                  fontSize: 36, height: 1.65, fontWeight: FontWeight.w700),
              baseHorizontalSpacing,
              baseVerticalSpacing,
              VerticalSpacing.zero,
              null),
          h2: DefaultTextBlockStyle(
              TextStyle(
                fontSize: 24,
                height: 1.65,
                fontWeight: FontWeight.w600,
              ),
              baseHorizontalSpacing,
              baseVerticalSpacing,
              VerticalSpacing.zero,
              null),
          h3: DefaultTextBlockStyle(
              TextStyle(
                  height: 1.65, fontSize: 20, fontWeight: FontWeight.w600),
              baseHorizontalSpacing,
              baseVerticalSpacing,
              VerticalSpacing.zero,
              null),
          paragraph: DefaultTextBlockStyle(
              defaultTextStyle.style.copyWith(fontSize: 20, height: 1.65),
              baseHorizontalSpacing,
              baseVerticalSpacing,
              VerticalSpacing.zero,
              null),
          lists: DefaultListBlockStyle(
              TextStyle(fontSize: 20, height: 1.65),
              baseHorizontalSpacing,
              baseVerticalSpacing,
              VerticalSpacing.zero,
              null,
              null),
          sizeHuge: TextStyle(
            height: 1.65,
            fontSize: 24,
            fontWeight: FontWeight.w500,
          ),
        ),
      ),
    );`

**Comment by dominikkeller** [comment]
@RJustoX 
I experienced something similar. In my case, it was due to the editor’s padding. Without the padding, it would select the line I wanted plus one extra, but not as many as 4-5 lines.

Still not optimal but usable.

**Comment by jonasbernardo** [comment]
@dominikkeller 
In my case this didn't work, the problem persists even with zero vertical space

**Comment by jonasbernardo** [comment]
This problem has a peculiarity, after you release the mouse it selects in the right place, but while you are holding the mouse button to select, it selects everything wrong, but after you release the mouse button in the right place, it selects the text correctly. The problem appears to be in this part of the selection rendering while the mouse button is being held to adjust the selection

**Comment by CatHood0** [comment]
This problem still seems strange to me. As such, the selection boxes are data that the `RenderParagraph` gives us given an offset/position (which is passed through the `RenderEditor` using `getOffsetForCaret` and similar methods. 

I wouldn't know how to help at this point since no matter how much I tried on web, desktop and mobile platforms, I couldn't reproduce this error.

**Comment by jonasbernardo** [comment]
@CatHood0 This problem is very serious, I am available to share my screen with you and show you the problem, we can use Google Meet

**Comment by CatHood0** [comment]
I apologize for the late response. I'm going to check this out right now and see how it goes.

**Comment by CatHood0** [comment]
@jonasbernardo 
@dominikkeller 

I cannot reproduce the issue even if i copy the example code and run in chrome.

https://github.com/user-attachments/assets/d0f2e7c8-8127-4757-9081-9bd8298dc9bc

**Comment by jonasbernardo** [comment]
https://github.com/user-attachments/assets/af541697-aaa2-4e14-94dd-1ce3b03dbe92

**Comment by jonasbernardo** [comment]
@CatHood0  
Try following these same steps in the video, I found it interesting that selecting something formatted with the header the selection works normally, but when selecting the paragraph without formatting it does not select correctly

**Comment by jonasbernardo** [comment]
the problem happens with both flutter 3.27.3 and flutter 3.29

**Comment by dominikkeller** [comment]
@CatHood0 
I somehow cant play your video. Maybe you can update it ?

Something seems to be different with our setups it seems.

**Comment by CatHood0** [comment]
@dominikkeller sorry, i'll update de video

**Comment by CatHood0** [comment]
> Try following these same steps in the video, I found it interesting that selecting something formatted with the header the selection works normally, but when selecting the paragraph without formatting it does not select correctly.

Probably we need to check the logic in `RenderEditableTextLine`

**Comment by Demetriox** [comment]
I have the same Issues came here for a solution... 
is it a RenderEditableTextLine problem?

**Comment by CatHood0** [comment]
I can't say for sure. It could be a logic issue just like it could be anything else. As i mentioned above, since i can't reproduce the problem yet, i'm unable to begin to check what could be wrong. I mentioned `RenderEditableTextLine` since it is responsible for handling the text selection.

**Comment by Demetriox** [comment]
https://github.com/user-attachments/assets/6e5d46a6-d512-4581-870b-0c2ba0b6a9f1

> In safari it does not happen, but on chrome It does, if that helps

Google Chrome
Chrome está actualizado
Versión 133.0.6943.127 (Build oficial) (arm64)

this is my chrome version

**Comment by CatHood0** [comment]
I have already updated to the latest version of flutter (3.29.0) and in the end, we are back to the same thing, I am not able to reproduce this problem. I used chrome and it worked exactly as I expected.

**Comment by CatHood0** [comment]
@EchoEllet If you have some free time, could you see if you are able to reproduce this issue in recent versions of Flutter?

**Comment by dominikkeller** [comment]
@CatHood0 
So I just upgraded to Flutter 3.29.0. So me setup is now:

Flutter Version: 3.29.0
flutter_quill: 11.0.0
flutter_quill_extensions: ^11.0.0
Chrome Version: 133.0.6943.127 (Official Build) (arm64)

Still no changes, and same issue.

**Comment by jonasbernardo** [comment]
me too

**Comment by EchoEllet** [comment]
I can confirm the issue, reproduced on Google Chrome using Flutter stable 3.29.0 Dart 3.7.0.

https://github.com/user-attachments/assets/fa6de8b1-6098-4693-b813-131a10681a12

**Comment by RJustoX** [comment]
I have this problem on windows 11> @EchoEllet I am noticing that something in common that all those who have been able to reproduce this problem have is that they use MacOS or an Apple operating system, although perhaps it is just a coincidence (I mention it because I use Debian, and I cannot reproduce the issue).

**Comment by ChiHoc** [comment]
For me, I encountered the same issue with Flutter's native TextField. When I tried replacing TextField with Quill, the problem still persisted. Maybe this issue is not related to Quill itself.

Flutter: 3.27.4
Chrome:  133.0.6943.142（Stable） (arm64)
MacOS: 15.1

**Comment by GuillermoDLCO** [comment]
I also have same issue.

Flutter: 3.27.4
flutter_quill: 11.0.0-dev.21
MacOS: 15.3.1

**Comment by theAugur** [comment]
Just wanted to confirm that I´m having the same issue when using quill editor in chrome.. both in windows and android. Oddly enough this does not happen when using firefox on windows.

Flutter: 3.29.2
flutter_quill: flutter_quill: ^11.1.0

**Comment by jezell** [comment]
Hey guys, put together a PR for tihs:

https://github.com/flutter/flutter/pull/165732

**Comment by CatHood0** [comment]
I knew I wasn't crazy! But I really didn't know where the problem lay in Flutter (I don't quite understand the project structure). I'm glad you're getting it fixed. Thanks for taking the time to do this and let us know!

**Comment by jezell** [comment]
Yeah you aren't crazy. It's impacting every editor and the core text fields. I've also seen it impacting super_editor and re_editor as well. Glad to help out. Seems to be a fairly widespread problem for anything editing text on web in the last few releases.

**Comment by aleripe** [comment]
> Hey guys, put together a PR for tihs:
> 
> [flutter/flutter#165732](https://github.com/flutter/flutter/pull/165732)
> 
> Fixes an issue in the Flutter engine

Unfortunately the fix doesn't work. Fixes the position while dragging, but makes it wrong when the mouse gets released...

**Comment by jezell** [comment]
@aleripe I discovered the real problem was a bit deeper in the engine and also impacted scrollbars due to improper mouse pointer calculation. 

If you are running Flutter 3.29.2 and want a patch so scrollbars and textboxes aren't screwed up. Replace your flutter_web_sdk in flutter/bin/cache with the one in here:

https://storage.googleapis.com/flutter-builds/releases/3.29.2/flutter_web_sdk.zip

Will push the patch to flock later this week. Let me know if you have issues with it. The mouse position is correct on drag and release. Also fixes the scrollbars.

**Comment by aleripe** [comment]
> [@aleripe](https://github.com/aleripe) I discovered the real problem was a bit deeper in the engine and also impacted scrollbars due to improper mouse pointer calculation.
> 
> If you are running Flutter 3.29.2 and want a patch so scrollbars and textboxes aren't screwed up. Replace your flutter_web_sdk in flutter/bin/cache with the one in here:
> 
> https://storage.googleapis.com/flutter-builds/releases/3.29.2/flutter_web_sdk.zip
> 
> Will push the patch to flock later this week. Let me know if you have issues with it. The mouse position is correct on drag and release. Also fixes the scrollbars.

Thanks for your kind reply! I just tried your patch and it works, indeed.
I fully understand your frustration, but PLEASE don't give up on Flutter. Their team is not the best, but the whole community is :)

**Comment by jezell** [comment]
Yeah not giving up on Flutter, just taking a different path. Anyone can always do a PR with any flock patch back to Flutter. I just would rather spend my time fixing things than fighting the system :)

**Comment by Demetriox** [comment]
Any updates? !!!

**Comment by marcio-ota** [comment]
> [@aleripe](https://github.com/aleripe) I discovered the real problem was a bit deeper in the engine and also impacted scrollbars due to improper mouse pointer calculation.
> 
> If you are running Flutter 3.29.2 and want a patch so scrollbars and textboxes aren't screwed up. Replace your flutter_web_sdk in flutter/bin/cache with the one in here:
> 
> https://storage.googleapis.com/flutter-builds/releases/3.29.2/flutter_web_sdk.zip
> 
> Will push the patch to flock later this week. Let me know if you have issues with it. The mouse position is correct on drag and release. Also fixes the scrollbars.

Works on 3.29.3 ?

**Comment by andrescastane** [comment]
Any updates? Is there any Flutter version where this error doesn’t occur?

I've tested it with flutter_quill version **10.8.3**, and the issue still persists, so it does seem very likely to be a Flutter engine issue as mentioned.
Also, everything works correctly on both Windows and macOS — I'm only experiencing this problem on Flutter Web.

If there’s a specific older version of Flutter where this bug doesn’t happen, I’d really appreciate knowing about it.

**Comment by BenDevExatech** [comment]
> Any updates? Is there any Flutter version where this error doesn’t occur?
> 
> I've tested it with flutter_quill version **10.8.3**, and the issue still persists, so it does seem very likely to be a Flutter engine issue as mentioned. Also, everything works correctly on both Windows and macOS — I'm only experiencing this problem on Flutter Web.
> 
> If there’s a specific older version of Flutter where this bug doesn’t happen, I’d really appreciate knowing about it.

I'm facing the same issue, and I can confirm that it occurs specifically on Web with Chrome engine (on Edge and Opera too), but it's OK with Firefox and Safari, also OK on Desktop.

I've tried the current fix version here :
https://github.com/flutter/flutter/pull/168217

Based on the last flutter_quill version 11.4.1 with flutter_quill_extensions version11.0.0, and unfortunately the pb still occurs...
It should be noted that the problem does not occur on a simple multi-line TextField.

**Comment by vishal9449** [comment]
When using Flutter on macOS, the TextEditingController correctly gets the selected text the first time. However, after the initial selection, it does not update or retrieve the new selection when the text is selected again.

**Comment by kayberd** [comment]
@BenDevExatech using 3.32.5 flutter and using master branch for flutter_quill package solved the issue for me. 11.4.2 will contain the fix but before that you can update your pubspec.yaml with 
```dart
flutter_quill:
    git:
      url: https://github.com/singerdmx/flutter-quill/
      ref: master
```
