### ISSUE TITLE
[Web] Issue with `flutter_keyboard_visibility_web` dependency when making a WASM build

### ISSUE THREAD

**Issue by geronimol** [singerdmx/flutter-quill#2473]
### Have you checked for an existing issue?

- [x] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill Version

10.8.5

### Steps to Reproduce

1. Create a new Flutter project and add `flutter_quill` and another dependency that depends on `flutter_keyboard_visibility`(e.g: `form_builder_extra_fields`).
2. Run app for web with `--wasm` flag

Tried adding this without success:
```dart
dependency_overrides:
    flutter_keyboard_visibility_web:
      git:
        url: https://github.com/EchoEllet/flutter_keyboard_visibility_temp_fork.git
        ref: master
        path: flutter_keyboard_visibility_web
```

What can I do?

### Expected results

Run without errors

### Actual results

`Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 254:
.dart_tool/flutter_build/a344d1ab8d8351ba59ccb75c8266ccee/web_plugin_registrant.dart:19:3: Error: 'FlutterKeyboardVisibilityPluginWeb' is imported from both
'package:flutter_keyboard_visibility_temp_fork/flutter_keyboard_visibility_web.dart' and 'package:flutter_keyboard_visibility_web/flutter_keyboard_visibility_web.dart'.
  FlutterKeyboardVisibilityPluginWeb.registerWith(registrar);
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Command: /Users/gero/fvm/versions/3.29.0/bin/cache/dart-sdk/bin/dart compile wasm --packages=/Users/gero/StudioProjects/wasm_test/.dart_tool/package_config.json
  --extra-compiler-option=--platform=/Users/gero/fvm/versions/3.29.0/bin/cache/flutter_web_sdk/kernel/dart2wasm_platform.dill -Ddart.vm.profile=false -Ddart.vm.product=false --extra-compiler-option=--import-shared-memory
  --extra-compiler-option=--shared-memory-max-pages=32768 -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_USE_SKWASM=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/f73bfc4522dd0bc87bbcdb4bb3088082755c5e87/
  --extra-compiler-option=--depfile=/Users/gero/StudioProjects/wasm_test/.dart_tool/flutter_build/a344d1ab8d8351ba59ccb75c8266ccee/dart2wasm.d -O0 --no-strip-wasm --extra-compiler-option=--enable-asserts -o
  /Users/gero/StudioProjects/wasm_test/.dart_tool/flutter_build/a344d1ab8d8351ba59ccb75c8266ccee/main.dart.wasm /Users/gero/StudioProjects/wasm_test/.dart_tool/flutter_build/a344d1ab8d8351ba59ccb75c8266ccee/main.dart`

**Comment by EchoEllet** [comment]
Could you try with [`11.0.0-dev.21`](https://pub.dev/packages/flutter_quill/versions/11.0.0-dev.21)?

**Comment by EchoEllet** [comment]
Fixed with latest version.

**Comment by geronimol** [comment]
@EchoEllet  Still not working for me. Were you able to reproduce?

**Comment by geronimol** [comment]
@EchoEllet Tried with and without dependency_overrides, always making a clean build and running `flutter pub upgrade`

If I don't use dependecy_overrides, it throws this:
` web_plugin_registrant.dart => package:flutter_keyboard_visibility_web => dart:html`

But when I use this override(that compiles when I only add `form_builder_extra_fields` to the project):
`  flutter_keyboard_visibility_web:
    git:
      url: https://github.com/raldhafiri/flutter_keyboard_visibility.git
      ref: master
      path: flutter_keyboard_visibility_web`
It throws this when I run `flutter run -d chrome --wasm`
`Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 254:
.dart_tool/flutter_build/a344d1ab8d8351ba59ccb75c8266ccee/web_plugin_registrant.dart:19:3: Error: 'FlutterKeyboardVisibilityPluginWeb' is imported from both
'package:flutter_keyboard_visibility_temp_fork/flutter_keyboard_visibility_web.dart' and 'package:flutter_keyboard_visibility_web/flutter_keyboard_visibility_web.dart'.
  FlutterKeyboardVisibilityPluginWeb.registerWith(registrar);
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Command: /Users/gero/fvm/versions/3.29.0/bin/cache/dart-sdk/bin/dart compile wasm --packages=/Users/gero/StudioProjects/wasm_test/.dart_tool/package_config.json
  --extra-compiler-option=--platform=/Users/gero/fvm/versions/3.29.0/bin/cache/flutter_web_sdk/kernel/dart2wasm_platform.dill -Ddart.vm.profile=false -Ddart.vm.product=false --extra-compiler-option=--import-shared-memory
  --extra-compiler-option=--shared-memory-max-pages=32768 -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_USE_SKWASM=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/f73bfc4522dd0bc87bbcdb4bb3088082755c5e87/
  --extra-compiler-option=--depfile=/Users/gero/StudioProjects/wasm_test/.dart_tool/flutter_build/a344d1ab8d8351ba59ccb75c8266ccee/dart2wasm.d -O0 --no-strip-wasm --extra-compiler-option=--enable-asserts -o
  /Users/gero/StudioProjects/wasm_test/.dart_tool/flutter_build/a344d1ab8d8351ba59ccb75c8266ccee/main.dart.wasm /Users/gero/StudioProjects/wasm_test/.dart_tool/flutter_build/a344d1ab8d8351ba59ccb75c8266ccee/main.dart`

[pubspec.lock.zip](https://github.com/user-attachments/files/18826986/pubspec.lock.zip)

**Comment by EchoEllet** [comment]
> Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 254:
../../.pub-cache/hosted/pub.dev/flutter_keyboard_visibility_web-2.0.0/lib/flutter_keyboard_visibility_web.dart:1:8: Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html' as html show window, Navigator;

The `flutter_quill` no longer depends on `flutter_keyboard_visibility_web` or `flutter_keyboard_visibility` so is this issue reproducible without `flutter_quill` and only `flutter_keyboard_visibility_web`?

**Comment by geronimol** [comment]
> The flutter_quill no longer depends on flutter_keyboard_visibility_web or flutter_keyboard_visibility so is this issue reproducible without flutter_quill and only form_builder_extra_fields?

`form_builder_extra_fields` works If I use dependency_overrides like so:
```dart
dependency_overrides:
  flutter_keyboard_visibility:
    git:
      url: https://github.com/raldhafiri/flutter_keyboard_visibility.git
      ref: master
      path: flutter_keyboard_visibility
  flutter_keyboard_visibility_web:
    git:
      url: https://github.com/raldhafiri/flutter_keyboard_visibility.git
      ref: master
      path: flutter_keyboard_visibility_web
``` 
Then if I add `flutter_quill` it throws the second error above because it seems there is a conflict with `flutter_keyboard_visibility_temp_fork` and `flutter_keyboard_visibility`

---
I was able to make a Wasm build by using the mentioned PR

**Comment by EchoEllet** [comment]
I see, one way to fix it is to simply rename [`FlutterKeyboardVisibilityPluginWeb`](https://github.com/EchoEllet/flutter_keyboard_visibility_temp_fork/blob/master/flutter_keyboard_visibility_web/lib/flutter_keyboard_visibility_web.dart#L7) to `FlutterKeyboardVisibilityTempForkPluginWeb`. I will update `flutter_keyboard_visibility_temp_fork` with the fix soon.

**Comment by EchoEllet** [comment]
The fix is to remove [`FlutterKeyboardVisibilityPluginWeb`](https://github.com/EchoEllet/flutter_keyboard_visibility_temp_fork/blob/master/flutter_keyboard_visibility_temp_fork/lib/flutter_keyboard_visibility_web.dart#L5-L12) class from `flutter_keyboard_visibility_temp_fork` (implemented for compatibility), I will publish a new version soon.

**Comment by geronimol** [comment]
Thanks!
