### ISSUE TITLE
Create the attributeBuilder method

### ISSUE THREAD

**Issue by luscuissiatto** [singerdmx/flutter-quill#7]
Is it possible to create an attributeBuilder method that works just like embedBuilder? I have the code below, but I can't customize the view

`{
       "attributes": {
         "list": "checked"
       },
       "insert": "\n"
     },
     {
       "attributes": {
         "list": "unchecked"
       },
       "insert": "\n"
     }`

**Comment by singerdmx** [comment]
We are trying to understand what you mean.
A little more clarification would be nice.
Also a pull request will be even better :)

**Comment by li3317** [comment]
Could you provide an example on what type of customization? Thank you!

**Comment by singerdmx** [comment]
If attributeBuilder is provided, how do you plan to use it?

**Comment by luscuissiatto** [comment]
Sorry, I'll try to explain it better. I have three types of lists in quill web (ordered, bookmark, check):
![image](https://user-images.githubusercontent.com/27908567/104364346-3e11b280-54f5-11eb-8ab8-9a892bc7bfdc.png)

Flutter-quill generates this:
![image](https://user-images.githubusercontent.com/27908567/104364496-71544180-54f5-11eb-9426-34b2db2b8881.png)

To generate a checklist, attributeBuilder would work like this:
![image](https://user-images.githubusercontent.com/27908567/104365627-fd1a9d80-54f6-11eb-83fd-7ba22e813ce0.png)


Does that make sense?

**Comment by singerdmx** [comment]
quill web has built-in **checked** ?
Could you provide delta string for this example?

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/104366249-ef045700-54cd-11eb-8a83-7d57833ee7a6.png)


You are trying to provide custom **leading**. See code above

**Comment by singerdmx** [comment]
```
Widget _buildLeading(BuildContext context, Line line, int index,
      Map<int, int> indentLevelCounts, int count) {
    DefaultStyles defaultStyles = QuillStyles.getStyles(context, false);
    Map<String, Attribute> attrs = line.style.attributes;
    if (attrs[Attribute.list.key] == Attribute.ol) {
      return _NumberPoint(
        index: index,
        indentLevelCounts: indentLevelCounts,
        count: count,
        style: defaultStyles.paragraph.style,
        attrs: attrs,
        width: 32.0,
        padding: 8.0,
      );
    }

    if (attrs[Attribute.list.key] == Attribute.ul) {
      return _BulletPoint(
        style:
            defaultStyles.paragraph.style.copyWith(fontWeight: FontWeight.bold),
        width: 32,
      );
    }
    if (attrs.containsKey(Attribute.codeBlock.key)) {
      return _NumberPoint(
        index: index,
        indentLevelCounts: indentLevelCounts,
        count: count,
        style: defaultStyles.code.style
            .copyWith(color: defaultStyles.code.style.color.withOpacity(0.4)),
        width: 32.0,
        attrs: attrs,
        padding: 16.0,
        withDot: false,
      );
    }
    return null;
  }
```

Currently we only support _NumberPoint and _BulletPoint

**Comment by luscuissiatto** [comment]
Yes, it's a custom leading. 

In Quill web version 1.3.7 there are three types of lists:
![image](https://user-images.githubusercontent.com/27908567/104367476-a2cf0c00-54f9-11eb-8afb-f18ba9a651be.png)

Generating the delta code:
`
[
     {
       "attributes": {
         "list": "ordered"
       },
       "insert": "\n"
     },
     {
       "insert": "Ordered list item"
     },
     {
       "attributes": {
         "list": "bullet"
       },
       "insert": "\n"
     },
     {
       "insert": "Bullet list item"
     },
     {
       "attributes": {
         "list": "unchecked"
       },
       "insert": "\n"
     },
     {
       "insert": "Checklist item"
     },
     {
       "attributes": {
         "list": "checked"
       },
       "insert": "\n"
     },
     {
       "insert": "Checklist item"
     },
   ]
`

**Comment by singerdmx** [comment]
Ok, if **check** is in official delta string, we can support that.
We will make changes or you can create pull request to modify _lib/widgets/text_block.dart_ if you cannot wait

**Comment by luscuissiatto** [comment]
thanks, i will send a pull request

**Comment by singerdmx** [comment]
Let's break it into two changes.
Make the toolbar change another commit (we can implement the toolbar change).

**Comment by singerdmx** [comment]
Also please add the json string in https://github.com/singerdmx/flutter-quill/blob/master/app/assets/sample_data.json
for the **check** attribute

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/104369641-9f745a00-54d2-11eb-80f3-3003c121b0a8.png)

Something like below:
"{"ops":[{"insert":"this is a check list"},{"attributes":{"list":"checked"},"insert":"\n"},{"insert":"this is a uncheck list"},{"attributes":{"list":"unchecked"},"insert":"\n"}]}"

**Comment by li3317** [comment]
Hello @luscuissiatto ! I added an attribute for check-in lib/models/documents/attribute.dart, we're also working on implementing the corresponding button in toolbar. We're happy to help implement the feature as some details such as on tap to check or uncheck may be a little tricky. Thank you!

**Comment by li3317** [comment]
Here is where the attribute is added : https://github.com/singerdmx/flutter-quill/commit/8b253517b494c91065f6abdef88d59317940ec1b

**Comment by li3317** [comment]
Here is where the attribute is added : https://github.com/singerdmx/flutter-quill/commit/4e61982222646e9bb8ebf5d4aeab5c5e48ac85f1

**Comment by li3317** [comment]
Hello @luscuissiatto , we've implemented the check box attribute for lists here : 170f3c62a7a0d942345e856fc1f7ef7a62f55333, feel free to check the commit and test it out! Thanks!

**Comment by singerdmx** [comment]
@li3317 I think you forgot to include change for editor.dart

**Comment by li3317** [comment]
Yes thanks for reminding, here's the commit : dfdd1b76677f71afbe7ffdcae5a9164425edcd41 , thanks!

**Comment by singerdmx** [comment]
@luscuissiatto @li3317 check out https://github.com/singerdmx/flutter-quill/commit/1913136d4f78ddac576bd2c286b0f9ff0313c559

**Comment by singerdmx** [comment]
Closing.
@luscuissiatto  this feature is implemented as of version 0.2.0

**Comment by luscuissiatto** [comment]
@singerdmx thank you so much

**Comment by EgorK0rshun** [comment]
if it's possible to use your own symbols for lists? For example, squares. Right now the implementation is only for lists with bullets, numbers and checkboxes.
there is only one validation in `text_block.dart` with the inability to return widgets depending on the attribute value
@singerdmx , sorry for the tag, but can customization of the sheets be supported?
